/**
 * The shape of the index artifact, which is the contract with the export pipeline.
 *
 * The artifact is generated by the capability-registry build and transformed into its
 * released envelope by the export pipeline's merge step. It contains ONLY data that has
 * already passed that side's outbound boundary. Nothing here is parsed from an OpenAPI spec
 * at runtime: if this half parsed specs it would become the boundary, and every gate (route
 * lint, vocabulary rule, intent lint, discovery denylist) would have to be reimplemented and
 * re-tested here. Reading a pre-projected index means the internal data is not in the
 * package at all.
 *
 * ONE FILE PER PRODUCT. The released artifact is `capability/<product>.capability-index.json`,
 * with the
 * product object at the top level under its own name. The plural `products` wrapper belonged
 * to the pre-release shape and implied multi-product files that never existed.
 */

/**
 * The envelope's format marker, for FUTURE shape changes.
 *
 * BOTH the released and the pre-release shapes claim 1, so this number cannot distinguish
 * them — `readIndexFile` shape-detects on the `products` wrapper instead. The check is still
 * worth keeping: it is what refuses a shape the generator has announced but this build does
 * not read.
 */
export const SUPPORTED_SCHEMA_VERSION = 1;

/** Envelope keys, i.e. everything at the top level that is NOT the product object. */
export const ENVELOPE_KEYS = [
  "schema_version",
  "version",
  "build_id",
  "harness_commit",
  "products",
] as const;

export type Mode = "read" | "write" | "destructive";

/** One parameter, under the name the OpenAPI spec itself gives it. */
export interface WireParam {
  name: string;
  type: string;
  required?: true;
  values?: unknown[];
  example?: unknown;
  description?: string;
  /** Field names/types one level inside an array item or nested object. */
  fields?: { name: string; type: string; required?: true }[];
  /**
   * Where a body field sits in the JSON, when that differs from its name. Published
   * because the nesting is not guessable and getting it wrong fails silently — tm's folder
   * create really wants `{folder: {name}}` while the spec's flat `{name}` is what a reader
   * would assume.
   */
  json_path?: string;
}

/**
 * A reference into a product-level lookup table.
 *
 * Named components are stored ONCE, already dereferenced and allOf-flattened at build time,
 * so resolution is a single dict lookup rather than a recursive $ref walk at runtime.
 */
export interface ComponentRef {
  $response?: string;
  $schema?: string;
}

/** A JSON Schema fragment, or a reference to a named one. */
export type SchemaNode = ComponentRef & Record<string, unknown>;

/** One declared response, or a reference to a named one. */
export interface ResponseDoc extends ComponentRef {
  description?: string;
  schema?: SchemaNode;
}

/** A capability, keyed by the endpoint it exposes. There is deliberately no name. */
export interface Capability {
  method: string;
  path: string;
  mode: Mode;
  entity: string;
  path_params?: WireParam[];
  query?: WireParam[];
  body?: WireParam[];
  intent?: string;
  /**
   * How to call the endpoint correctly.
   *
   * ABSENT from the released artifact — the export dropped it, and the shape-change note
   * does not say whether that was intended. Kept optional and still scored by search so the
   * server works either way; nothing may depend on it being present.
   */
  guidance?: string[];
  /** Allowlisted row fields. Absent when `shape` is "discovered". */
  returns?: string[];
  /** "discovered" when the product declares no response schema for this operation. */
  shape?: "discovered";
  requires?: string[];
  paginated?: boolean;
  /** The largest page the operation declares. */
  max_page_size?: number;
  /**
   * Declared responses by status code, values possibly `{$response: "Name"}` references.
   *
   * ADDITIVE and not yet emitted: no capability in the current export carries it. Absence
   * means "no response schema available", never an error. Resolve with `resolveComponent`.
   */
  responses?: Record<string, ResponseDoc>;
}

export interface EntityDoc {
  title?: string;
  aliases?: string[];
  id_convention?: string;
  parents?: string[];
  relations?: { entity?: string; via?: string }[];
  [key: string]: unknown;
}

/**
 * Paging controls, keyed "METHOD /path".
 *
 * NOT USED BY THIS SERVER: it performs one request and returns the response, so paging
 * belongs to the caller and the page parameters are published with the endpoint's other
 * query parameters. The field is still emitted by the build, so it stays described here
 * rather than silently ignored — a consumer that DOES page can use it.
 */
export interface PagingRule {
  page?: string;
  size?: string;
  /** The largest page the operation declares. Absent when the spec states no maximum. */
  max?: number;
}

export interface ProductIndex {
  summary: string;
  /**
   * The single host this product is served from, when it has one.
   *
   * A default, not the last word: config overrides it, and for a region-sharded product
   * (one declaring `base_urls`) account discovery outranks it and this is the fallback.
   */
  base_url?: string;
  /**
   * Candidate regional hosts, in probe order, for a product whose host depends on the
   * ACCOUNT rather than the deployment.
   *
   * Declaring these makes the product region-sharded: the server asks each in turn with the
   * caller's credentials and keeps the one that answers. A single fixed `base_url` cannot
   * express this — it would send every account outside the default region to the wrong host,
   * a failure invisible to anyone testing from inside that region.
   */
  base_urls?: string[];
  /**
   * The endpoint to probe the candidates with. Derived from the capabilities when absent
   * (see `discovery.probePath`); declare it when the derived choice would be wrong.
   */
  probe_path?: string;
  capabilities: Capability[];
  entities: Record<string, EntityDoc>;
  paging?: Record<string, PagingRule>;
  /** Named responses, referenced as `{$response: "Name"}`. Additive; not yet emitted. */
  responses?: Record<string, ResponseDoc>;
  /** Named schemas, referenced as `{$schema: "Name"}`. Additive; not yet emitted. */
  schemas?: Record<string, SchemaNode>;
}

/** Where one product's data came from. Logging and cache-busting only. */
export interface Provenance {
  /** `<commit>_<UTC timestamp>` in the released shape. */
  build_id: string;
  /** Dotted content-generation counter, e.g. "1.2". Absent in the pre-release shape. */
  version?: string;
}

/**
 * The merged, in-memory model: every loaded file's product under its own name.
 *
 * This is the server's own structure, not the file format — one file carries one product,
 * and the registry holds all of them so a caller can search across products.
 */
export interface RegistryIndex {
  schema_version: number;
  build_id: string;
  products: Record<string, ProductIndex>;
}
