/**
 * The shape of the index artifact, which is the contract with the Python build.
 *
 * The artifact is generated by `capability-registry/scripts/build_index.py` and contains
 * ONLY data that has already passed that side's outbound boundary. Nothing here is parsed
 * from an OpenAPI spec at runtime: if this half parsed specs it would become the boundary,
 * and every gate (route lint, vocabulary rule, intent lint, discovery denylist) would have
 * to be reimplemented and re-tested here. Reading a pre-projected index means the internal
 * data is not in the package at all.
 */

/** Bumped by the generator when the artifact's shape changes. */
export const SUPPORTED_SCHEMA_VERSION = 1;

export type Mode = "read" | "write" | "destructive";

/** One parameter, under the name the OpenAPI spec itself gives it. */
export interface WireParam {
  name: string;
  type: string;
  required?: true;
  values?: unknown[];
  example?: unknown;
  description?: string;
  /** Field names/types one level inside an array item or nested object. */
  fields?: { name: string; type: string; required?: true }[];
  /**
   * Where a body field sits in the JSON, when that differs from its name. Published
   * because the nesting is not guessable and getting it wrong fails silently — tm's folder
   * create really wants `{folder: {name}}` while the spec's flat `{name}` is what a reader
   * would assume.
   */
  json_path?: string;
}

/** A capability, keyed by the endpoint it exposes. There is deliberately no name. */
export interface Capability {
  method: string;
  path: string;
  mode: Mode;
  entity: string;
  path_params?: WireParam[];
  query?: WireParam[];
  body?: WireParam[];
  intent?: string;
  guidance?: string[];
  /** Allowlisted row fields. Absent when `shape` is "discovered". */
  returns?: string[];
  /** "discovered" when the product declares no response schema for this operation. */
  shape?: "discovered";
  requires?: string[];
  paginated?: true;
  max_items?: number;
}

export interface EntityDoc {
  title?: string;
  aliases?: string[];
  id_convention?: string;
  parents?: string[];
  relations?: { entity?: string; via?: string }[];
  [key: string]: unknown;
}

/**
 * Paging controls, keyed "METHOD /path".
 *
 * These live BESIDE the capabilities rather than on them, and deliberately. The page and
 * size parameter names are the resolver's, not the caller's — publishing them invites a
 * caller to drive paging itself, which is what burned the call budget on 17 Aug. Whoever
 * RUNS the request still needs them, so they travel here: `resolve` reads this map and the
 * search tool never echoes it, leaving the published surface unchanged.
 */
export interface PagingRule {
  page?: string;
  size?: string;
  /** The largest page the operation declares. Absent when the spec states no maximum. */
  max?: number;
}

export interface ProductIndex {
  summary: string;
  /**
   * The host the HARNESS declares for this product, if any. Config overrides it — the same
   * precedence Atlas uses. Absent for tm, whose product.yaml deliberately leaves the host
   * to config so that per-account region sharding can be honoured.
   */
  base_url?: string;
  capabilities: Capability[];
  entities: Record<string, EntityDoc>;
  paging?: Record<string, PagingRule>;
}

export interface RegistryIndex {
  schema_version: number;
  build_id: string;
  harness_commit?: string;
  products: Record<string, ProductIndex>;
}
