#!/bin/bash
# Percy MCP — First-time setup
# Creates your local config from the example template

set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$DIR/config"
EXAMPLE="$DIR/config.example"

echo "╔══════════════════════════════════════╗"
echo "║      Percy MCP — First-Time Setup    ║"
echo "╚══════════════════════════════════════╝"
echo ""

# Check if config already exists
if [ -f "$CONFIG" ]; then
  echo "Config already exists at: $CONFIG"
  echo ""
  read -p "Overwrite? (y/N) " -n 1 -r
  echo ""
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Keeping existing config."
    exit 0
  fi
fi

echo "Enter your BrowserStack credentials:"
echo "(Find them at https://www.browserstack.com/accounts/settings)"
echo ""

read -p "BrowserStack Username: " BS_USERNAME
read -p "BrowserStack Access Key: " BS_ACCESS_KEY
echo ""

echo "Enter your Percy token (optional — can be set later):"
echo "(Find it in your Percy project settings)"
echo ""

read -p "Percy Token (press Enter to skip): " PERCY_TOKEN_VAL
echo ""

# Write config
cat > "$CONFIG" << CONF
# Percy MCP Configuration
# Generated by setup.sh — DO NOT COMMIT THIS FILE

export BROWSERSTACK_USERNAME="$BS_USERNAME"
export BROWSERSTACK_ACCESS_KEY="$BS_ACCESS_KEY"
CONF

if [ -n "$PERCY_TOKEN_VAL" ]; then
  echo "export PERCY_TOKEN=\"$PERCY_TOKEN_VAL\"" >> "$CONFIG"
else
  echo "# export PERCY_TOKEN=\"\"" >> "$CONFIG"
fi

echo "# export PERCY_ORG_TOKEN=\"\"" >> "$CONFIG"

echo ""
echo "✓ Config saved to: $CONFIG"
echo ""
echo "Next steps:"
echo "  1. Restart Claude Code"
echo "  2. Try: 'Use percy_auth_status'"
echo "  3. Or: 'Use percy_create_project with name my-app'"
echo ""

# Create profiles directory
mkdir -p "$DIR/profiles"

echo "To save org profiles for quick switching:"
echo "  cp $CONFIG $DIR/profiles/my-org-name"
echo "  ./switch-org.sh my-org-name"
